//! Bevy messages for world update events, e.g. chunk generation messages.

use bevy::ecs::message::Message;
use bevy::math::IVec2;
use bevy::prelude::Entity;
use meloncraft_chunk::Chunk;

/// Message indicating that a client has requested a chunk be sent to them, or that a chunk should
/// be loaded for a player because the server detected they are within render distance of it.
///
/// ## Writing
/// You should write this message when you want to request a chunk be sent to a client.
/// This is typically done when a client first connects to the server, or when they move into render
/// distance of a new chunk and the server detects this and wants to load the chunk for them.
///
/// ## Reading
/// You should read this message and simply *forward* it; i.e. write new message(s) related to chunk
/// loading when you receive this. These could include:
/// - Checking if the chunk has already been generated before.
/// - If it has been generated, writing a [`SendChunk`] message to send the chunk to the client.
/// - If it has not been generated, writing a [`GenerateChunk`] message to request the chunk to be
///   generated by whatever chunk generation system you have in place.
#[derive(Message, Debug, Clone, Eq, PartialEq)]
pub struct ChunkRequest {

    /// The client that requested the chunk.
    /// This should be the entity ID of the player who should be sent the chunks, e.g. the player
    /// that went within render distance of the chunk and caused it to be loaded, or the player that
    /// just connected to the server and should be sent chunks.
    pub client: Entity,

    /// The position of the chunk this message refers to.
    /// Type is a Bevy [`IVec2`], like an `(i32, i32)`.
    /// This is the chunk position, not the block position; i.e. the coordinates of the chunk in the
    /// chunk grid, not the coordinates of a block within the chunk. For example, the chunk containing
    /// the block at block coordinates `(100, 50, -100)` would be at chunk coordinates `(6, -7)`,
    /// since each chunk is 16 blocks wide and chunk coordinates are calculated by dividing block
    /// coordinates by 16 and flooring the result.
    pub chunk_pos: IVec2,
}

/// Message indicating that a chunk has been generated, and is ready to store in the world and be sent
/// to the client who requested it.
///
/// ## Writing
/// You should write this message when a chunk has been generated and is ready to be sent to the client
/// who requested it. This is typically done by your chunk generation system, after it has generated a
/// chunk in response to a [`GenerateChunk`] message.
/// 
/// ## Reading
/// You should read this message and do any required logic. You may also wish to forward another
/// message, e.g.:
/// - Write a [`SendChunk`] message to send the chunk to the client who requested it. You can get
///   the client from the [`ChunkGenerated::requested_by`] field, which will be `Some(Entity)` if the
///   chunk was generated in response to a [`ChunkRequest`] message from a player.
/// - Store the chunk in the world, e.g. by inserting it into a chunk storage resource. You can get the
///   chunk's position from the [`ChunkGenerated::chunk_pos`] field, and the chunk data itself from the
///   [`ChunkGenerated::chunk`] field.
#[derive(Message, Debug, Clone, Eq, PartialEq)]
pub struct ChunkGenerated {

    /// Optional client that requested the chunk. Can be `None` if the chunk was generated for some
    /// other reason, e.g. pre-generating chunks.
    /// This should be the entity ID of the player who should be sent the chunks, e.g. the player
    /// that went within render distance of the chunk and caused it to be loaded, or the player that
    /// just connected to the server and should be sent chunks.
    pub requested_by: Option<Entity>,

    /// The position of the chunk this message refers to.
    /// Type is a Bevy [`IVec2`], like an `(i32, i32)`.
    /// This is the chunk position, not the block position; i.e. the coordinates of the chunk in the
    /// chunk grid, not the coordinates of a block within the chunk. For example, the chunk containing
    /// the block at block coordinates `(100, 50, -100)` would be at chunk coordinates `(6, -7)`,
    /// since each chunk is 16 blocks wide and chunk coordinates are calculated by dividing block
    /// coordinates by 16 and flooring the result.
    pub chunk_pos: IVec2,

    /// The actual generated chunk data. This should be a fully generated chunk, ready to be sent to
    /// the client and stored in the world or whatever any listening systems want to do with it.
    /// See [`Chunk`] for the format of this data structure.
    pub chunk: Chunk,
}

#[derive(Message, Debug, Clone)]
pub struct SendChunk {
    pub client: Entity,
    pub chunk_pos: IVec2,
    pub chunk: Chunk,
}

#[derive(Message, Debug, Clone)]
pub struct GenerateChunk {
    pub requested_by: Entity,
    pub chunk_pos: IVec2,
}
