//! Bevy messages for world update events, e.g. chunk generation messages.

use bevy::ecs::message::Message;
use bevy::prelude::Entity;
use meloncraft_chunk::Chunk;

/// Message indicating that a client has requested a chunk be sent to them, or that a chunk should
/// be loaded for a player because the server detected they are within render distance of it.
///
/// ## Writing
/// You should write this message when you want to request a chunk be sent to a client.
/// This is typically done when a client first connects to the server, or when they move into render
/// distance of a new chunk and the server detects this and wants to load the chunk for them.
///
/// ## Reading
/// You should read this message and simply *forward* it; i.e. write new message(s) related to chunk
/// loading when you receive this. These could include:
/// - Checking if the chunk has already been generated before.
/// - If it has been generated, writing a [`SendChunk`] message to send the chunk to the client.
/// - If it has not been generated, writing a [`GenerateChunk`] message to request the chunk to be
///   generated by whatever chunk generation system you have in place.
#[derive(Message, Debug, Clone, Eq, PartialEq)]
pub struct ChunkRequest {
    pub client: Entity,
    pub chunk_x: i32,
    pub chunk_z: i32,
}

#[derive(Message, Debug, Clone, Eq, PartialEq)]
pub struct ChunkGenerated {
    pub requested_by: Option<Entity>,
    pub chunk_x: i32,
    pub chunk_z: i32,
    pub chunk: Chunk,
}

#[derive(Message, Debug, Clone)]
pub struct SendChunk {
    pub client: Entity,
    pub chunk_x: i32,
    pub chunk_z: i32,
    pub chunk: Chunk,
}

#[derive(Message, Debug, Clone)]
pub struct GenerateChunk {
    pub requested_by: Entity,
    pub chunk_x: i32,
    pub chunk_z: i32,
}
