//! Bevy messages for world update events, e.g. chunk generation messages.

use bevy::ecs::message::Message;
use bevy::math::IVec2;
use bevy::prelude::Entity;
use meloncraft_chunk::Chunk;

/// Message indicating that a client has requested a chunk be sent to them, or that a chunk should
/// be loaded for a player because the server detected they are within render distance of it.
///
/// ## Writing
/// You should write this message when you want to request a chunk be sent to a client.
/// This is typically done when a client first connects to the server, or when they move into render
/// distance of a new chunk and the server detects this and wants to load the chunk for them.
///
/// ## Reading
/// You should read this message and simply *forward* it; i.e. write new message(s) related to chunk
/// loading when you receive this. These could include:
/// - Checking if the chunk has already been generated before.
/// - If it has been generated, writing a [`SendChunk`] message to send the chunk to the client.
/// - If it has not been generated, writing a [`GenerateChunk`] message to request the chunk to be
///   generated by whatever chunk generation system you have in place.
#[derive(Message, Debug, Clone, Eq, PartialEq)]
pub struct ChunkRequest {

    /// The client that requested the chunk.
    /// This should be the entity ID of the player who should be sent the chunks, e.g. the player
    /// that went within render distance of the chunk and caused it to be loaded, or the player that
    /// just connected to the server and should be sent chunks.
    pub client: Entity,
    pub chunk_pos: IVec2,
}

#[derive(Message, Debug, Clone, Eq, PartialEq)]
pub struct ChunkGenerated {
    pub requested_by: Option<Entity>,
    pub chunk_pos: IVec2,
    pub chunk: Chunk,
}

#[derive(Message, Debug, Clone)]
pub struct SendChunk {
    pub client: Entity,
    pub chunk_pos: IVec2,
    pub chunk: Chunk,
}

#[derive(Message, Debug, Clone)]
pub struct GenerateChunk {
    pub requested_by: Entity,
    pub chunk_pos: IVec2,
}
