use crate::ServerboundPacket;
use crate::network_messages::ServerboundNetworkPacket;
use bevy::prelude::{Entity, Message};
use meloncraft_client::connection_state::ConnectionState;
use meloncraft_protocol_types::{ProtocolBuffer as _, ProtocolType as _, VarInt};

/// Used to send a chat message to the server. The message may not be longer than 256 characters
/// or else the server will kick the client.
///
/// The server should broadcast a Player Chat Message packet with Chat Type minecraft:chat to all
/// players that haven't disabled chat (including the player that sent the message).
/// See Java Edition protocol/Chat#Processing chat for more information.
#[derive(Message, Debug, Clone)]
pub struct ServerboundChat {
    pub client: Entity,

    /// Content of the message.
    /// This is a raw string, no formatting..
    pub message: String,

    /// The time the client sent the message.
    /// Number of milliseconds since the epoch (1 Jan 1970, midnight, UTC).
    pub timestamp: u64,

    /// The salt used to verify the signature hash. Randomly generated by the client.
    pub salt: u64,

    /// The signature used to verify the chat message's authentication. When present, always 256 bytes and not length-prefixed.
    /// This is a SHA256 with RSA digital signature computed over the following:
    ///
    /// - The number 1 as a 4-byte int. Always 00 00 00 01.
    /// - The player's 16-byte UUID.
    /// - The chat session (a 16-byte UUID randomly generated by the client).
    /// - The index of the message within this chat session as a 4-byte int. First message is 0, next message is 1, etc. Incremented each time the client sends a chat message.
    /// - The salt (from above) as an 8-byte long.
    /// - The timestamp (from above) converted from milliseconds to seconds, so divide by 1000, as an 8-byte long.
    /// - The length of the message in bytes (from above) as a 4-byte int.
    /// - The message bytes.
    /// - The number of messages in the last seen set, as a 4-byte int. Always in the range [0,20].
    /// - For each message in the last seen set, from oldest to newest, the 256-byte signature of that message.
    ///
    /// The client's chat private key is used for the message signature.
    pub signature: Option<Vec<u8>>,

    /// Number of signed clientbound chat messages the client has seen from the server since the
    /// last serverbound chat message from this client. The server will use this to update its last
    /// seen list for the client.
    pub message_count: i32,

    /// Fixed `BitSet` (20).
    /// Bitmask of which message signatures from the last seen set were used to sign this message.
    /// The most recent is the highest bit. If there are fewer than 20 messages in the last seen
    /// set, the lower bits will be zeros.
    pub acknowledged: [u8; 3],

    /// Checksum is computed over all the message signature checksums in the last seen set, from
    /// oldest to newest. Both the packet checksum and signature checksums use the same logic as
    /// Java's Arrays.hashCode(byte[]) implementation. The packet checksum additionally casts the
    /// resulting int to a byte, and if that byte is 0 returns 1, otherwise returns said byte.
    pub checksum: u8,
}

impl ServerboundPacket for ServerboundChat {
    fn id() -> i32 {
        return 0x08;
    }
    fn state() -> ConnectionState {
        return ConnectionState::Play;
    }
    fn deserialize(mut packet: ServerboundNetworkPacket) -> Option<Self> {
        let message = packet.data.net_deserialize().ok()?;
        let timestamp = packet.data.net_deserialize().ok()?;
        let salt = packet.data.net_deserialize().ok()?;
        let signature = bool::net_deserialize(&mut packet.data)
            .ok()?
            .then(|| return packet.data.drain(0..256).collect());
        let message_count = VarInt::net_deserialize(&mut packet.data).ok()?.0;

        let mut acknowledged = [0_u8; 3];
        acknowledged[0] = packet.data.net_deserialize().ok()?;
        acknowledged[1] = packet.data.net_deserialize().ok()?;
        acknowledged[2] = packet.data.net_deserialize().ok()?;

        let checksum = packet.data.net_deserialize().ok()?;

        return Some(Self {
            client: packet.client,
            message,
            timestamp,
            salt,
            signature,
            message_count,
            acknowledged,
            checksum,
        });
    }
}
