//! Module for struct component [`Uuid`].

use bevy::ecs::component::Component;

/// The *universally unique identifier* (`UUID`) defining the entity.
/// Every entity (including players) will have a UUID.
///
/// ## Protocol representation
/// UUIDs are represented by a `u128`. See [`Uuid`] for more information.
///
/// # Uniqueness
/// This is basically guaranteed to be a completely random identifier, never seen before. This
/// means it is safe (and recommended) to use UUIDs to represent a player or entity in, for example,
/// in playerdata storage of a world.
/// In online-mode, UUIDs are generated by Mojang's authentication servers, and are effectively
/// guaranteed to be unique across all Minecraft accounts.
/// In offline-mode, UUIDs are generated from the player's username, and are not guaranteed to be
/// unique. This means that in offline-mode, multiple players can attempt to join with the same
/// UUID, which can cause many issues. It is recommended to reject any connections if the UUID they
/// try to log in as is already playing on the server, or, some disconnect the existing connection
/// and accept the new one.
///
/// ## Static
/// UUIDs are static: an entity can't change its UUID like they can with a name.
/// This means it is recommended to identify entities by their [`Uuid`] rather than
/// by their name / [`Username`](`crate::Username`), as names can be changed, but UUIDs can't.
///
/// ## Protocol representation
/// UUIDs are represented by two consecutive `u64`s. For convenience, `ProtocolType` is implemented
/// on both [`Uuid`] and `u128`, so you can just call `.net_serialize()` and `.net_deserialize()`.
#[derive(Component, Debug, Clone)]
pub struct Uuid(pub u128);
